on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  accurics-scan:
    runs-on: ubuntu-latest
    name: accurics-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Accurics Scan
        id: accurics-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://894d-103-141-116-119.ngrok.io/v1/api/terrascan
          webhook_token: fdc8c264-ff73-4dfd-8801-32952e9f8b5d