on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  accurics-scan:
    runs-on: ubuntu-latest
    name: accurics-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Accurics Scan
        id: accurics-scan
        uses: docker://accurics/terrascan-action:latest
        with:
          only_warn: true
          verbose: true
          webhook_url: https://devenv.accurics.com/v1/api/terrascan
          webhook_token: f3e570d5-b36c-49f3-a412-8f122ef5d5b3