on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          only_warn: true
          verbose: true
          webhook_url: https://6b20-106-77-9-14.ngrok.io/v1/api/terrascan
          webhook_token: 1874f65f-c463-40f3-a3cf-cfda7fdc807c