on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://5dd2-96-244-150-213.ngrok.io/v1/api/terrascan
          notification_webhook_token: 6e685800-7a22-4b50-a683-3e50140b679b
          repo_url: https://github.com/test-org-pankaj/solid-octo-enigma.git