on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://ded7-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: 9bd6f09a-5879-4e04-a515-f04aadde6a6d
          repo_url: https://github.com/test-org-pankaj/solid-octo-enigma.git