on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://84ab-96-244-150-213.ngrok.io/v1/api/terrascan
          notification_webhook_token: 679faf6f-a81c-4eab-9e8c-b68de35598db
          repo_url: https://github.com/test-org-pankaj/solid-octo-enigma.git