on:
  push:
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: docker://nasirrabbani/terrascan-action:test3
        with:
          only_warn: true
          verbose: true
          notification_webhook_url: https://2a68-103-83-214-125.ngrok.io/v1/api/terrascan
          notification_webhook_token: d9cbca8e-3451-4317-b4ca-5197ff1dcc0b
          repo_url: https://github.com/test-org-pankaj/solid-octo-enigma.git