on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          only_warn: true
          verbose: true
          webhook_url: https://df32-103-141-116-117.ngrok.io/v1/api/terrascan
          webhook_token: 678229b2-ed6c-41a8-b215-c5edb08a2b72