on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Accurics Scan
        id: terrascan
        uses: accurics/terrascan-action@main
        with:
          only_warn: true
          verbose: true
          webhook_url: https://e476-103-141-116-117.ngrok.io/v1/api/terrascan
          webhook_token: b1b1aca8-29c4-4cd4-a70e-597843a7c637